### ISSUE TITLE
Can't Open - Damaged

### ISSUE THREAD

**Issue by davisstu** [progcode/spotify-silicon#1]
Downloaded v1.0 on my Macbook Air M1 - latest 11.4 Mac OS and get the following when trying to launch it:

![image](https://user-images.githubusercontent.com/8912521/121663105-fab87180-ca9d-11eb-811e-6980827227b3.png)

**Comment by progcode** [comment]
you can rebuild with the following command: nativefier "`nativefier "https://play.spotify.com" --inject ./build/assets/js/service-worker-fix.js --icon ./build/assets/icons/spotify-multi-size.icns -a arm64 --widevine --internal-urls ".*" --name="SpotifySilicon" --app-version 1.0.0 --build-version 100 --width 1440 --height 900 --min-width 1440 --min-height 900 --fast-quit --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" --disable-dev-tools`"
